MyGoidaList_db/Models/AddTitleViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace MyGoidaList.Models
{
    public class AddTitleViewModel
    {
        public int UserId { get; set; }
        public int TitleId { get; set; }
        public int MaxEpisodes { get; set; }
        public string Status { get; set; }
        public int Episodes { get; set; }
        public int Score { get; set; }
    }
}

MyGoidaList_db/Models/UserTitle.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace MyGoidaList.Models
{
    [PrimaryKey(nameof(UserId), nameof(TitleId))]
    public class UserTitle
    {
        public int UserId { get; set; }

        public int TitleId { get; set; }

        public string Status { get; set; }
        public int Episodes { get; set; }
        public int Score { get; set; }

        public virtual User User { get; set; }
        public virtual Title Title { get; set; }
    }
}

MyGoidaList_db/Controllers/UserTitleController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using Microsoft.AspNetCore.Mvc;
using MyGoidaList.Models;
using System.Net;
using Microsoft.EntityFrameworkCore;
//using Newtonsoft.Json;

namespace MyGoidaList.Controllers
{
    public class UserTitleController : Controller
    {
        private ApplicationDbContext db;

        public UserTitleController(ApplicationDbContext db)
        {
            this.db = db;
        }

        public ActionResult Index(int userId)
        {
            var user = db.Users
                .Include(u => u.UserTitles)       // Включаем коллекцию UserTitles
                .ThenInclude(ut => ut.Title)      // Включаем связанные Title для каждого UserTitle
                .FirstOrDefault(u => u.Id == userId);

            if (user == null)
            {
                return NotFound(); // Обработка случая, если пользователь не найден
            }

            ViewBag.UserId = userId;
            ViewBag.UserName = user.Nickname;

            // Передаём связанные UserTitles в представление
            return View(user.UserTitles);
        }


        public ActionResult Edit(int userId, int titleId)
        {
            var userTitle = db.UserTitles
                .FirstOrDefault(ut => ut.UserId == userId && ut.TitleId == titleId);

            if (userTitle == null)
            {
                return NotFound();
            }

            var title = db.Titles.FirstOrDefault(t => t.Id == titleId);
            if (title == null)
            {
                return NotFound();
            }

            var viewModel = new EditTitleViewModel
            {
                UserId = userTitle.UserId,
                TitleId = userTitle.TitleId,
                Episodes = userTitle.Episodes,
                Score = userTitle.Score,
                MaxEpisodes = title.Episodes
            };

            return View(viewModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(EditTitleViewModel model)
        {
            if (!ModelState.IsValid)
            {
                return View(model);
            }

            var userTitle = db.UserTitles
                .FirstOrDefault(ut => ut.UserId == model.UserId && ut.TitleId == model.TitleId);

            if (userTitle == null)
            {
                return NotFound();
            }

            var title = db.Titles.FirstOrDefault(t => t.Id == model.TitleId);
            if (title == null)
            {
                return NotFound();
            }

            if (model.Episodes > title.Episodes)
            {
                ModelState.AddModelError("Episodes", "The number of episodes cannot exceed the total episodes for the title.");
                return View(model);
            }

            userTitle.Status = model.Status;
            userTitle.Episodes = model.Episodes;
            userTitle.Score = model.Score;

            db.SaveChanges();

            return RedirectToAction("Index", new { userId = model.UserId });
        }


        public ActionResult Delete(int userId, int titleId)
        {
            var userTitle = db.UserTitles.FirstOrDefault(ut => ut.UserId == userId && ut.TitleId == titleId);

            if (userTitle == null)
            {
                return NotFound();
            }

            return View(userTitle);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int userId, int titleId)
        {
            var userTitle = db.UserTitles
                .FirstOrDefault(ut => ut.UserId == userId && ut.TitleId == titleId);

            if (userTitle == null)
            {
                return NotFound();
            }

            db.UserTitles.Remove(userTitle);

            var user = db.Users.FirstOrDefault(u => u.Id == userId);
            if (user != null && user.TitlesSum > 0)
            {
                user.TitlesSum--;
            }

            db.SaveChanges();

            return RedirectToAction("Index", new { userId = userId });
        }


        public ActionResult AddTitle(int userId)
        {
            var titles = db.Titles.ToList();

            var userTitles = db.UserTitles.Where(ut => ut.UserId == userId).Select(ut => ut.TitleId).ToList();

            var availableTitles = titles.Where(t => !userTitles.Contains(t.Id)).ToList();

            var model = new AddTitleListViewModel
            {
                UserId = userId,
                Titles = availableTitles
            };

            return View(model);
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult AddTitle(AddTitleViewModel model)
        {
            if (model.TitleId != null && model.UserId != null)
            {
                var userTitle = new UserTitle
                {
                    UserId = model.UserId,
                    TitleId = model.TitleId,
                    Status = model.Status,
                    Episodes = model.Episodes,
                    Score = model.Score
                };

                db.UserTitles.Add(userTitle);
                db.SaveChanges();

                var user = db.Users.FirstOrDefault(u => u.Id == model.UserId);
                if (user != null)
                {
                    user.TitlesSum += 1;
                    db.SaveChanges();
                }

                return RedirectToAction("AddTitle", new { userId = model.UserId });
            }

            return View(model);
        }

        public ActionResult AddTitleForm(int userId, int titleId)
        {
            var title = db.Titles.FirstOrDefault(t => t.Id == titleId);

            if (title == null)
            {
                return NotFound();
            }

            var model = new AddTitleViewModel
            {
                UserId = userId,
                TitleId = titleId,
                MaxEpisodes = title.Episodes
            };

            return View(model);
        }
    }
}

MyGoidaList_db/Views/UserTitle/AddTitle.cshtml
@model MyGoidaList.Models.AddTitleListViewModel

@{
    ViewBag.Title = "Add Title to User";
}

<h2>Add Titles</h2>

@if (Model.Titles.Any())
{
    <ul>
        @foreach (var title in Model.Titles)
        {
            <li>
                @Html.ActionLink($"{title.Name}", "AddTitleForm", new { userId = Model.UserId, titleId = title.Id })
            </li>
        }
    </ul>
}
else
{
    <p>No available titles to add.</p>
}

MyGoidaList_db/Views/UserTitle/AddTitleForm.cshtml
@model MyGoidaList.Models.AddTitleViewModel

@{
    ViewBag.Title = "Add Title to User";
}

<h2>Add Title to User</h2>

@using (Html.BeginForm("AddTitle", "UserTitle", FormMethod.Post))
{
    @Html.AntiForgeryToken()

    @Html.HiddenFor(m => m.UserId)
    @Html.HiddenFor(m => m.TitleId)

    <div class="form-group">
        <label for="Status">Status</label>
        @Html.TextBoxFor(m => m.Status, new { @class = "form-control" })
        @Html.ValidationMessageFor(m => m.Status)
    </div>

    <div class="form-group">
        <label for="Episodes">Episodes</label>
        @Html.TextBoxFor(m => m.Episodes, new { @class = "form-control", type = "number", min = "0", max = Model.MaxEpisodes })
        @Html.ValidationMessageFor(m => m.Episodes)
    </div>

    <div class="form-group">
        <label for="Score">Score</label>
        @Html.TextBoxFor(m => m.Score, new { @class = "form-control", type = "number", min = "0", max = "10"})
        @Html.ValidationMessageFor(m => m.Score)
    </div>

    <button type="submit" class="btn btn-success">Add Title</button>
    @Html.ActionLink("Back to Titles List", "AddTitle", new { userId = Model.UserId }, new { @class = "btn btn-secondary" })
}

MyGoidaList_db/Views/UserTitle/Delete.cshtml
@model MyGoidaList.Models.UserTitle

@{
    ViewBag.Title = "Delete Title";
}

<h2>Delete Title</h2>

<div>
    <h4>Are you sure you want to delete this title?</h4>
    <dl class="dl-horizontal">
        <dt>Title</dt>
        <dd>@Model.TitleId</dd>

        <dt>Episodes</dt>
        <dd>@Model.Episodes</dd>

        <dt>Score</dt>
        <dd>@Model.Score</dd>
    </dl>
</div>

@using (Html.BeginForm("Delete", "UserTitle", FormMethod.Post))
{
    @Html.AntiForgeryToken()
    @Html.HiddenFor(model => model.UserId)
    @Html.HiddenFor(model => model.TitleId)

    <button type="submit" class="btn btn-danger">Delete</button>
    @Html.ActionLink("Cancel", "Index", new { userId = Model.UserId }, new { @class = "btn btn-secondary" })
}

MyGoidaList_db/Views/UserTitle/Edit.cshtml
@model MyGoidaList.Models.EditTitleViewModel

@{
    ViewBag.Title = "Edit Title";
}

<h2>Edit Title</h2>

@using (Html.BeginForm("Edit", "UserTitle", FormMethod.Post))
{
    @Html.AntiForgeryToken()

    @Html.HiddenFor(model => model.UserId)
    @Html.HiddenFor(model => model.TitleId)

    <div class="form-group">
        <label for="Status">Status</label>
        @Html.TextBoxFor(m => m.Status, new { @class = "form-control" })
        @Html.ValidationMessageFor(m => m.Status)
    </div>

    <div class="form-group">
        <label for="Episodes">Episodes</label>
        @Html.TextBoxFor(model => model.Episodes, new { @class = "form-control", type = "number", min = "1", max = Model.MaxEpisodes })
        @Html.ValidationMessageFor(model => model.Episodes)
    </div>

    <div class="form-group">
        <label for="Score">Score</label>
        @Html.TextBoxFor(model => model.Score, new { @class = "form-control", type = "number", min = "0", max = "10"})
        @Html.ValidationMessageFor(model => model.Score)
    </div>

    <button type="submit" class="btn btn-primary">Save</button>
    @Html.ActionLink("Cancel", "Index", new { userId = Model.UserId }, new { @class = "btn btn-secondary" })
}

MyGoidaList_db/Views/UserTitle/Index.cshtml
@model IEnumerable<MyGoidaList.Models.UserTitle>

@{
    ViewBag.Title = $"{ViewBag.UserName}'s Titles";
}

<h2>@ViewBag.UserName's Titles</h2>

<p>
    @Html.ActionLink("Add New Title", "AddTitle", new { userId = ViewBag.UserId }, new { @class = "btn btn-success" })
</p>

<table class="table">
    <thead>
        <tr>
            <th>Title Name</th>
            <th>Status</th>
            <th>Episodes</th>
            <th>Score</th>
            <th>Actions</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var userTitle in Model)
        {
            <tr>
                <td>@userTitle.Title.Name</td>
                <td>@userTitle.Status</td>
                <td>@userTitle.Episodes</td>
                <td>@userTitle.Score</td>
                <td>
                    @Html.ActionLink("Edit", "Edit", new { userId = userTitle.UserId, titleId = userTitle.TitleId }, new { @class = "btn btn-primary btn-sm" })
                    @Html.ActionLink("Delete", "Delete", new { userId = userTitle.UserId, titleId = userTitle.TitleId }, new { @class = "btn btn-danger btn-sm" })
                </td>
            </tr>
        }
    </tbody>
</table>